apiVersion: v1
kind: Pod
metadata:
  annotations:
    agones.dev/container: simple-game-server
    agones.dev/ready-container-id: containerd://5017999b9bb7954b209c69781d0aa2ebfc4e533c0083b6490133040ba933d2e8
    agones.dev/sdk-version: 1.30.0
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  creationTimestamp: "2023-08-11T04:06:24Z"
  labels:
    agones.dev/gameserver: sd-agones-fleet-klxgw-fj2lz
    agones.dev/role: gameserver
    agones.dev/safe-to-evict: "false"
    manager: controller
    operation: Update
    time: "2023-08-11T04:08:47Z"
  name: sd-agones-fleet-klxgw-fj2lz
  namespace: default
  ownerReferences:
  - apiVersion: agones.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: GameServer
    name: sd-agones-fleet-klxgw-fj2lz
    uid: 1e11d464-9750-4ea4-ba27-ad146075170d
  resourceVersion: "1558759"
  uid: 32022c5b-1463-4227-b6ec-6b7184d915dc
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              agones.dev/role: gameserver
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - --grpc-port=9357
    - --http-port=9358
    env:
    - name: GAMESERVER_NAME
      value: sd-agones-fleet-klxgw-fj2lz
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: FEATURE_GATES
      value: CountsAndLists=false&CustomFasSyncInterval=true&Example=false&FleetAllocationOverflow=false&PlayerAllocationFilter=false&PlayerTracking=false&PodHostname=false&ResetMetricsOnDelete=false&SDKGracefulTermination=true&SafeToEvict=true&SplitControllerAndExtensions=false&StateAllocationFilter=true
    image: us-docker.pkg.dev/agones-images/release/agones-sdk:1.30.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    name: agones-gameserver-sidecar
    resources:
      requests:
        cpu: 30m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kfdl5
      readOnly: true
  - env:
    - name: AGONES_SDK_GRPC_PORT
      value: "9357"
    - name: AGONES_SDK_HTTP_PORT
      value: "9358"
    image: us-central1-docker.pkg.dev/happyaigc/sd-repository-2b6bae98/game-server:tf
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /gshealthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: simple-game-server
    ports:
    - containerPort: 7654
      hostPort: 7235
      protocol: UDP
    resources:
      limits:
        cpu: 20m
        memory: 64Mi
      requests:
        cpu: 20m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: empty
      readOnly: true
  - command:
    - /bin/sh
    - start.sh
    env:
    - name: AGONES_SDK_GRPC_PORT
      value: "9357"
    - name: AGONES_SDK_HTTP_PORT
      value: "9358"
    image: us-central1-docker.pkg.dev/happyaigc/sd-repository-2b6bae98/sd-webui:tf
    imagePullPolicy: IfNotPresent
    name: stable-diffusion-webui
    ports:
    - containerPort: 7860
      hostPort: 7541
      protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /stable-diffusion-webui/models
      name: stable-diffusion-storage
      subPath: models
    - mountPath: /result
      name: stable-diffusion-storage
      subPath: result
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kfdl5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: sd-agones-fleet-klxgw-fj2lz
  nodeName: gke-tf-gen-gke-2b6ba-nvidia-tesla-t4--fa7cf408-xjw4
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: agones-sdk
  serviceAccountName: agones-sdk
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
  volumes:
  - name: stable-diffusion-storage
    persistentVolumeClaim:
      claimName: vol1
  - emptyDir: {}
    name: empty
  - name: kube-api-access-kfdl5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-11T04:06:56Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-11T04:07:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-11T04:07:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-11T04:06:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ba76e8732e826eb5ebdb8dd5e3efc75cf494beda0cadd80c2e842cf648aab6a8
    image: us-docker.pkg.dev/agones-images/release/agones-sdk:1.30.0
    imageID: us-docker.pkg.dev/agones-images/release/agones-sdk@sha256:7fd13b658bbb505f3e6e528c192533ba63c0e97fc092a5148d8e04fbd6f47ad4
    lastState: {}
    name: agones-gameserver-sidecar
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-08-11T04:07:00Z"
  - containerID: containerd://5017999b9bb7954b209c69781d0aa2ebfc4e533c0083b6490133040ba933d2e8
    image: us-central1-docker.pkg.dev/happyaigc/sd-repository-2b6bae98/game-server:tf
    imageID: us-central1-docker.pkg.dev/happyaigc/sd-repository-2b6bae98/game-server@sha256:1e4f61c5617f2873f55381a5748bfdd3d680debe73f8ae86e34a8391f1fec6e9
    lastState: {}
    name: simple-game-server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-08-11T04:07:00Z"
  - containerID: containerd://b7b2eb7976cc725e0297e67317017abd64047a4f7f1cd133403223decb1e7a6a
    image: us-central1-docker.pkg.dev/happyaigc/sd-repository-2b6bae98/sd-webui:tf
    imageID: us-central1-docker.pkg.dev/happyaigc/sd-repository-2b6bae98/sd-webui@sha256:97e2b4ff7281e8da1810c707f363746e946a6b34a275c55b3185e5e3616ffa93
    lastState: {}
    name: stable-diffusion-webui
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-08-11T04:07:00Z"
  hostIP: 10.10.0.52
  phase: Running
  podIP: 10.68.3.14
  podIPs:
  - ip: 10.68.3.14
  qosClass: Burstable
  startTime: "2023-08-11T04:06:56Z"
