apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: sd-agones-fleet
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      container: simple-game-server
      ports:
      - container: simple-game-server
        containerPort: 7654
        name: default
      - container: stable-diffusion-webui
        containerPort: 7860
        name: sd
        protocol: TCP
      template:
        spec:
          containers:
          - image: us-central1-docker.pkg.dev/happyaigc/sd-repository-c8c84f4c/game-server:tf
            name: simple-game-server
            resources:
              limits:
                cpu: 20m
                memory: 64Mi
              requests:
                cpu: 20m
                memory: 64Mi
          - command:   # 这里改成自己的启动命令
            - /bin/sh
            - -c
            - start_supervisor2.sh
            image: us-central1-docker.pkg.dev/happyaigc/sd-repository-c8c84f4c/sd-webui:stt1 # 这里改成自己的镜像
            name: stable-diffusion-webui
            resources:
              limits:
                nvidia.com/gpu: "1"
            volumeMounts:
            - mountPath: /yuanxiao_root_nfs   # 这里改成自己的nfs挂载路径
              name: stable-diffusion-storage
              subPath: " "  # 这里留个空格
          nodeSelector:
            cloud.google.com/gke-nodepool: nvidia-tesla-t4-nodepool
          volumes:
          - name: stable-diffusion-storage
            persistentVolumeClaim:
              claimName: vol1
