apiVersion: v1
kind: Pod
metadata:
  name: sdwebui-debug1
  namespace: default  # 如果不是这个命名空间,则修改
  labels:
    app: sdwebui-debug # change_other_model
spec:
  nodeSelector: # Add this nodeSelector block, must be gpu node, 这里配合下面的 nvidia.com/gpu: "1"使用 --- add by yx
    cloud.google.com/gke-nodepool: nvidia-tesla-t4-nodepool
  volumes:
    - name: stable-diffusion-storage
      persistentVolumeClaim:
        claimName: vol1
  containers:
    - name: sdwebui-debug
      image: us-central1-docker.pkg.dev/happyaigc/sd-repository-c8c84f4c/sd-webui:stt11
      # command: ["bash","-c","sleep 3600;"] # 测试用
      # command: ["bash","-c","./start_debug.sh"] # debug用
      # command: ["bash","-c","./start.sh"]  # 正式命令
      command: ["bash","-c","./start_supervisor2_debug.sh"] # debug用
      # command: ["bash","-c","./start_supervisor2.sh"] # 正式命令
      args: []
      volumeMounts:
        - mountPath: "/yuanxiao_root_nfs"
          name: stable-diffusion-storage
          # subPath: "/" # 不允许这样写,会报错
          subPath: ' ' #这样写不会报错,也是挂载到filestore的根目录,后面留个空格即可
      resources:
        limits:
          # cpu: 5000m
          # memory: 20Gi
          nvidia.com/gpu: 1
        
