apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stable-diffusion-nginx
  name: stable-diffusion-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stable-diffusion-nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stable-diffusion-nginx
    spec:
      automountServiceAccountToken: true
      containers:
      - image: us-central1-docker.pkg.dev/happyaigc/sd-repository-fa4db6b4/nginx:tf
        imagePullPolicy: IfNotPresent
        name: stable-diffusion-nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeSelector:
        cloud.google.com/gke-nodepool: nvidia-tesla-t4-nodepool
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30